name: UI Tests

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'
      - 'test/e2e/frontend/**'
      - 'test/unit/frontend/**'
      - 'package.json'
  pull_request:
    paths:
      - 'frontend/**'
      - 'test/e2e/frontend/**'
      - 'test/unit/frontend/**'
      - 'package.json'

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Install NPM dependencies
      - name: Install Dependencies
        run: npm ci
      - name: Run Linting Tests
        run: npm run lint
      # and run all Cypress tests
      - name: Run UI Unit Tests
        run: npm run cover:unit:frontend
      - name: Run UI E2E (Cypress) Tests - OS
        uses: cypress-io/github-action@v4
        with:
          install: false
          config-file: config/cypress-os.config.js
          build: npm run build
          start: npm run cy:web-server:os
      - name: Run UI E2E (Cypress) Tests - EE
        uses: cypress-io/github-action@v4
        with:
            install: false
            config-file: config/cypress-ee.config.js
            build: npm run build
            start: npm run cy:web-server:ee
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-output
          path: |
            test/e2e/frontend/cypress/screenshots
            test/e2e/frontend/cypress/videos
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: frontend